source 'https://github.com/CocoaPods/Specs.git'

workspace 'GLInterop'

platform :ios, '8.0'

target 'GLInterop_Example' do
  #use_frameworks!
  pod 'GLInterop', :path => '../'

  target 'GLInterop_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
